---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-dummy-service-deployment
  labels:
    app: py-dummy-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py-dummy-service
  template:
    metadata:
      labels:
        app: py-dummy-service
    spec:
      securityContext:
        runAsUser: 5000
        runAsGroup: 5000
      containers:
      - name: py-dummy-service
        image: bcochofel/py-dummy-service:0.9.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1