name: Release
on:
  push:
    branches:
      - main
    paths:
      - 'config.py'
      - 'setup.*'
      - 'Dockerfile'
      - 'py_dummy_service/*'
      - 'charts/py-dummy-service/*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.8
        with:
          versionSpec: '5.x'
      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.8
        id: gitversion
      - name: Changelog
        id: changelog
        uses: nuuday/github-changelog-action@v1.0.0
        with:
          next_version: "${{ steps.gitversion.outputs.majorMinorPatch }}"
      - name: Bump version
        run: |
          sed -i "s/\(__app_version__ = \"\).*\(\"\)/\1$VER\2/g" py_dummy_service/__init__.py
          sed -i "s/\(appVersion: \).*$/\1$VER/g" charts/py-dummy-service/Chart.yaml
          sed -i "s/\(version: \).*$/\1$VER/g" charts/py-dummy-service/Chart.yaml
          sed -i "s/\(tag: \"\).*\(\"\)/\1$VER\2/g" charts/py-dummy-service/values.yaml
        env:
          VER: ${{ steps.gitversion.outputs.majorMinorPatch }}
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.gitversion.outputs.majorMinorPatch }}
          release_name: Release ${{ steps.gitversion.outputs.majorMinorPatch }}
          body: |
            [CHANGELOG](./CHANGELOG.md)
          draft: false
          prerelease: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bcochofel/py-dummy-service:${{ steps.gitversion.outputs.majorMinorPatch }}
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}